#!/usr/bin/env bash
# This script of loops from 1 to 10 displays "bad luck" for the 4th loop iteration,"good luck" for the 8th loop iteration and "Best school" for the other iterations

counter=1

while [ $counter -le 10 ]
do
  if [ $counter -eq 4 ]
  then
    echo "bad luck"
  elif [ $counter -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((counter++))
done
