#!/usr/bin/env bash
# display the content of the current directory

for files=(*)

if [ ${#files[@]} -eq 0 ]; then
  echo "The directory is empty."
else
  for file in "${files[@]}"; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
      name=$(echo "$file" | cut -d'-' -f2-)
      echo " - $name"
    fi
  done
fi
